# http://gitpod.io/#github.com/gnolang/getting-started-workshop

additionalRepositories:
  - url: https://github.com/gnolang/gno
    checkoutLocation: gno

tasks:
  - name: Gno Deps
    env:
      GNO_ROOT: '../gno'
    init: make deps

ports:
  - name: gnoweb
    description: "the Gno.land web server"
    port: 8888

  - name: "gnodev RPC"
    description: "the RPC server, managed by tendermint2"
    port: 26657
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - harry-hov.gno
