# http://gitpod.io/#github.com/gnolang/getting-started-workshop

additionalRepositories:
  - url: https://github.com/gnolang/gno
    checkoutLocation: gno

tasks:
  - name: Checkout Version
    init: git -C ../gno 79a71a47f987c5fad28be73b56ac7d3691774840

  - name: Install Deps
    init: make -C ../gno/misc/devdeps install

  - name: Install Gno
    init: go -C ../gno/gnovm install -v ./cmd/gno

  - name: Install Gnoweb & Gnoland
    init: go -C ../gno/gno.land install -v ./cmd/gnoweb ./cmd/gnoland ./cmd/gnokey

  - name: Install Gnodev
    init: go -C ../gno/contribs/gnodev install -v ./cmd/gnodev

ports:
  - name: gnoweb
    description: "the Gno.land web server"
    port: 8888

  - name: "gnodev RPC"
    description: "the RPC server, managed by tendermint2"
    port: 26657
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - harry-hov.gno
