# http://gitpod.io/#github.com/gnolang/getting-started-workshop

additionalRepositories:
  - url: https://github.com/gnolang/gno
    checkoutLocation: gno
  - url: https://github.com/gnolang/gnopls
    checkoutLocation: gnopls


tasks:
  - name: Gno Deps
    before: git -C ../gno checkout 3b42391db98f7be35a99f9a060b589f6b69fd3e3
    init: |
      # add work and sync
      go -C .. work init && go -C .. work add -r . && go -C .. work sync
      # install gno dev deps
      make -C ../gno/misc/devdeps install
      # install gno
      go -C ../gno/gnovm install -v ./cmd/gno
      # install gnoweb, gnoland, gnokey
      go -C ../gno/gno.land install -v ./cmd/gnoweb ./cmd/gnoland ./cmd/gnokey
      # install gnodev
      go -C ../gno/contribs/gnodev install -v ./cmd/gnodev
      # exit
      echo "Deps installed"

ports:
  - name: gnoweb
    description: "the Gno.land web server"
    port: 8888

  - name: "gnodev RPC"
    description: "the RPC server, managed by tendermint2"
    port: 26657
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - harry-hov.gno
